/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/components/ButtonCommon/ButtonCommon.Style`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/components/ButtonCommon/ButtonCommon`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/services/authService`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/services/errorService`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/services/toastService`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/navigations/AuthStack`; params?: Router.UnknownInputParams; } | { pathname: `/navigations/MainStack`; params?: Router.UnknownInputParams; } | { pathname: `/navigations/Router`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Auth/Login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Auth/Login/Login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Auth/Login/LoginScreen.Style`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Main/Home/Home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Main/Home/Home.Style`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Main/Home`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/App`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/app/components/ButtonCommon/ButtonCommon.Style`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/app/components/ButtonCommon/ButtonCommon`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/app/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/app/services/authService`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/app/services/errorService`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/app/services/toastService`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/navigations/AuthStack`; params?: Router.UnknownOutputParams; } | { pathname: `/navigations/MainStack`; params?: Router.UnknownOutputParams; } | { pathname: `/navigations/Router`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Auth/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Auth/Login/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Auth/Login/LoginScreen.Style`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Main/Home/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Main/Home/Home.Style`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Main/Home`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/App${`?${string}` | `#${string}` | ''}` | `/../src/app/components/ButtonCommon/ButtonCommon.Style${`?${string}` | `#${string}` | ''}` | `/../src/app/components/ButtonCommon/ButtonCommon${`?${string}` | `#${string}` | ''}` | `/../src/app/index${`?${string}` | `#${string}` | ''}` | `/../src/app/services/authService${`?${string}` | `#${string}` | ''}` | `/../src/app/services/errorService${`?${string}` | `#${string}` | ''}` | `/../src/app/services/toastService${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/navigations/AuthStack${`?${string}` | `#${string}` | ''}` | `/navigations/MainStack${`?${string}` | `#${string}` | ''}` | `/navigations/Router${`?${string}` | `#${string}` | ''}` | `/screens/Auth/Login${`?${string}` | `#${string}` | ''}` | `/screens/Auth/Login/Login${`?${string}` | `#${string}` | ''}` | `/screens/Auth/Login/LoginScreen.Style${`?${string}` | `#${string}` | ''}` | `/screens/Main/Home/Home${`?${string}` | `#${string}` | ''}` | `/screens/Main/Home/Home.Style${`?${string}` | `#${string}` | ''}` | `/screens/Main/Home${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/components/ButtonCommon/ButtonCommon.Style`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/components/ButtonCommon/ButtonCommon`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/services/authService`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/services/errorService`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/services/toastService`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/navigations/AuthStack`; params?: Router.UnknownInputParams; } | { pathname: `/navigations/MainStack`; params?: Router.UnknownInputParams; } | { pathname: `/navigations/Router`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Auth/Login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Auth/Login/Login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Auth/Login/LoginScreen.Style`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Main/Home/Home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Main/Home/Home.Style`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Main/Home`; params?: Router.UnknownInputParams; };
    }
  }
}
